[package]
name = "flamingo"
version = "0.1.0"
edition = "2024"

[dependencies]
flamingo-config = { path = "../flamingo-config" }
flamingo-path = { path = "../flamingo-path" }
flamingo-context = { path = "../flamingo-context" }
flamingo-logger = { path = "../flamingo-logger" }
flamingo-err = { path = "../flamingo-err" }
log = { version = "0.4.27", features = [ "std" ] }
rayon = "1.10.0"
clap = { version = "4.5.51", features = [ "derive" ] }
