[package]
name = "flamingo-context"
version = "0.1.0"
edition = "2024"

[dependencies]
flamingo-git = { path = "../flamingo-git" }
flamingo-path = { path = "../flamingo-path" }
flamingo-config = { path = "../flamingo-config" }
flamingo-err = { path = "../flamingo-err" }
bitflags = "2.10.0"
log = "0.4.28"
